name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'doctora-spring-boot/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'doctora-spring-boot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./doctora-spring-boot

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: docker build -t doctora-backend:${{ github.sha }} .

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backend-jar
        path: doctora-spring-boot/target/*.jar
